# Usamos una imagen oficial y liviana de Nginx
FROM nginx:alpine

# Copiamos la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos tus carpetas de diseño adentro del directorio público de Nginx
COPY templates /usr/share/nginx/html/templates
COPY static /usr/share/nginx/html/static

# Nginx por defecto corre en el puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]